version: "3.9"
services:
  frontend:
    image: golatex-frontend
    container_name: golatex-frontend-container
    ports:
      - "3006:3006"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: npm run dev
volumes:
  node_modules:
